/// Flutter icons Social
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Social
///      fonts:
///       - asset: fonts/Social.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class Social {
  Social._();

  static const _kFontFam = 'Social';
  static const _kFontPkg = 'sayko_assets';

  static const IconData apple = IconData(
    0xf179,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData google = IconData(
    0xf1a0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
